# Generated by Django 4.2.7 on 2024-01-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('complete', 'complete')], default='pending', max_length=25),
        ),
    ]
